language: cpp

compiler:
  - clang

before_install:
  - pyenv install 3.6.0
  - pip install requests

script:
  - g++ -O0 -g -coverage -fprofile-arcs -ftest-coverage -std=c++11 -o tests test/main.cpp
  - ./tests
  - gcov -r . -o . test/main.cpp
  - bash <(curl -s https://codecov.io/bash)
  
